name: Deploy to Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute deploy script on server
        uses: appleboy/ssh-action@master
        with:
          host: 164.90.245.198
          username: root
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: /root/deployment.sh
