name: Deploy to Digital Ocean

on:
  push:
    branches: [main]

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: root
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /root/codi-api
            git pull origin main
            npm install
            pm2 restart codi-api
            echo "Deployment successful!"
